KB@DESKTOP-5AL75G7 MINGW64 ~/Desktop/30JoursDePython/Day23 (main)
$ mkdir mon_projet

FKB@DESKTOP-5AL75G7 MINGW64 ~/Desktop/30JoursDePython/Day23 (main)
$ cd mon_projet

FKB@DESKTOP-5AL75G7 MINGW64 ~/Desktop/30JoursDePython/Day23/mon_projet (main)
$ python -m venv env

FKB@DESKTOP-5AL75G7 MINGW64 ~/Desktop/30JoursDePython/Day23/mon_projet (main)
$ env\Scripts\activate
bash: envScriptsactivate: command not found

FKB@DESKTOP-5AL75G7 MINGW64 ~/Desktop/30JoursDePython/Day23/mon_projet (main)
$ Dir
env

FKB@DESKTOP-5AL75G7 MINGW64 ~/Desktop/30JoursDePython/Day23/mon_projet (main)
$ Venv\scripts\activer
bash: Venvscriptsactiver: command not found

FKB@DESKTOP-5AL75G7 MINGW64 ~/Desktop/30JoursDePython/Day23/mon_projet (main)
$ Venv\ scripts \Venv\scripts\Venv\.activer
bash: Venv scripts: command not found

FKB@DESKTOP-5AL75G7 MINGW64 ~/Desktop/30JoursDePython/Day23/mon_projet (main)
$ PIP Freeze
ERROR: unknown command "Freeze" - maybe you meant "freeze"

FKB@DESKTOP-5AL75G7 MINGW64 ~/Desktop/30JoursDePython/Day23/mon_projet (main)
$
